### ISSUE TITLE
Support for El Capitan?

### ISSUE THREAD

**Issue by rememberlenny** [pivotal-sprout/sprout-wrap#86]
I have tried to get this running on a new computer with El Capitan. 

I keep getting an error.

Any suggestions?

```
[2016-01-27T17:34:10-05:00] INFO: Starting Chef Run for C02QQ1AFFVH8.local
[2016-01-27T17:34:10-05:00] INFO: Running start handlers
[2016-01-27T17:34:10-05:00] INFO: Start handlers complete.
Compiling Cookbooks...
"/Users/leonardbogdonoff"
[2016-01-27T17:34:10-05:00] WARN: Cloning resource attributes for directory[/var/chef/cache] from prior resource (CHEF-3694)
[2016-01-27T17:34:10-05:00] WARN: Previous directory[/var/chef/cache]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/recipes/var_chef_cache.rb:3:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Current  directory[/var/chef/cache]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/recipes/homebrew.rb:11:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Doing cask ccmenu
[2016-01-27T17:34:10-05:00] WARN: Doing cask firefox
[2016-01-27T17:34:10-05:00] WARN: Doing cask flycut
[2016-01-27T17:34:10-05:00] WARN: Doing cask rowanj-gitx
[2016-01-27T17:34:10-05:00] WARN: Doing cask github
[2016-01-27T17:34:10-05:00] WARN: Doing cask google-chrome
[2016-01-27T17:34:10-05:00] WARN: Doing cask google-drive
[2016-01-27T17:34:10-05:00] WARN: Doing cask google-hangouts
[2016-01-27T17:34:10-05:00] WARN: Doing cask macvim
[2016-01-27T17:34:10-05:00] WARN: Doing cask skype
[2016-01-27T17:34:10-05:00] WARN: Doing cask textmate
[2016-01-27T17:34:10-05:00] WARN: Doing cask vagrant
[2016-01-27T17:34:10-05:00] WARN: Doing cask virtualbox
[2016-01-27T17:34:10-05:00] WARN: Doing cask xquartz
[2016-01-27T17:34:10-05:00] WARN: Doing cask xscope
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula ctags-exuberant
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula ag
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula chromedriver
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula imagemagick
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula node
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula pstree
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula qt
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula ssh-copy-id
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula tmux
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula tree
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula watch
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula wget
[2016-01-27T17:34:10-05:00] WARN: Doing homebrew formula rbenv-binstubs
[2016-01-27T17:34:10-05:00] WARN:  The 'sprout-terminal' cookbook works inconsistently while Terminal is running
[2016-01-27T17:34:10-05:00] WARN: Cloning resource attributes for homebrew_package[git] from prior resource (CHEF-3694)
[2016-01-27T17:34:10-05:00] WARN: Previous homebrew_package[git]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/homebrew/recipes/default.rb:41:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Current  homebrew_package[git]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-git/recipes/install.rb:3:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Cloning resource attributes for directory[/Users/leonardbogdonoff/workspace] from prior resource (CHEF-3694)
[2016-01-27T17:34:10-05:00] WARN: Previous directory[/Users/leonardbogdonoff/workspace]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/recipes/workspace_directory.rb:1:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Current  directory[/Users/leonardbogdonoff/workspace]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-git/recipes/projects.rb:23:in `block in from_file'
[2016-01-27T17:34:10-05:00] WARN: Cloning resource attributes for directory[/Users/leonardbogdonoff/Library/LaunchAgents] from prior resource (CHEF-3694)
[2016-01-27T17:34:10-05:00] WARN: Previous directory[/Users/leonardbogdonoff/Library/LaunchAgents]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-homebrew/recipes/launchctl.rb:3:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Current  directory[/Users/leonardbogdonoff/Library/LaunchAgents]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-mysql/recipes/install.rb:14:in `block in from_file'
[2016-01-27T17:34:10-05:00] WARN: Cloning resource attributes for directory[/Users/leonardbogdonoff/Library/LaunchAgents] from prior resource (CHEF-3694)
[2016-01-27T17:34:10-05:00] WARN: Previous directory[/Users/leonardbogdonoff/Library/LaunchAgents]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-mysql/recipes/install.rb:14:in `block in from_file'
[2016-01-27T17:34:10-05:00] WARN: Current  directory[/Users/leonardbogdonoff/Library/LaunchAgents]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-postgresql/recipes/add_launch_agent.rb:4:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Cloning resource attributes for directory[/var/chef/cache] from prior resource (CHEF-3694)
[2016-01-27T17:34:10-05:00] WARN: Previous directory[/var/chef/cache]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/recipes/homebrew.rb:11:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Current  directory[/var/chef/cache]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-osx-apps/recipes/textmate.rb:7:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Cloning resource attributes for execute[link textmate] from prior resource (CHEF-3694)
[2016-01-27T17:34:10-05:00] WARN: Previous execute[link textmate]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-osx-apps/recipes/textmate.rb:26:in `from_file'
[2016-01-27T17:34:10-05:00] WARN: Current  execute[link textmate]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-osx-apps/recipes/textmate.rb:38:in `from_file'
Converging 196 resources
Recipe: sprout-base::var_chef_cache
  * directory[/var/chef/cache] action create[2016-01-27T17:34:11-05:00] INFO: Processing directory[/var/chef/cache] action create (sprout-base::var_chef_cache line 3)
[2016-01-27T17:34:11-05:00] INFO: directory[/var/chef/cache] group changed to 80
[2016-01-27T17:34:11-05:00] INFO: directory[/var/chef/cache] mode changed to 777

    - change mode from '0775' to '0777'
    - change group from 'staff' to 'admin'
Recipe: sprout-base::bash_it
  * git[/var/chef/cache/bash_it] action sync[2016-01-27T17:34:11-05:00] INFO: Processing git[/var/chef/cache/bash_it] action sync (sprout-base::bash_it line 3)
 (up to date)
  * directory[/Users/leonardbogdonoff/.bash_it] action create[2016-01-27T17:34:11-05:00] INFO: Processing directory[/Users/leonardbogdonoff/.bash_it] action create (sprout-base::bash_it line 10)
[2016-01-27T17:34:11-05:00] INFO: directory[/Users/leonardbogdonoff/.bash_it] mode changed to 777

    - change mode from '0755' to '0777'
  * execute[Copying bash-it's .git to /Users/leonardbogdonoff/.bash_it] action run[2016-01-27T17:34:11-05:00] INFO: Processing execute[Copying bash-it's .git to /Users/leonardbogdonoff/.bash_it] action run (sprout-base::bash_it line 15)
[2016-01-27T17:34:11-05:00] INFO: execute[Copying bash-it's .git to /Users/leonardbogdonoff/.bash_it] ran successfully

    - execute rsync -axSH /var/chef/cache/bash_it/ /Users/leonardbogdonoff/.bash_it
  * template[/Users/leonardbogdonoff/.bash_profile] action create[2016-01-27T17:34:11-05:00] INFO: Processing template[/Users/leonardbogdonoff/.bash_profile] action create (sprout-base::bash_it line 20)
 (up to date)
  * sprout_base_bash_it_enable_feature[aliases/general] action create[2016-01-27T17:34:11-05:00] INFO: Processing sprout_base_bash_it_enable_feature[aliases/general] action create (sprout-base::bash_it line 29)
 (up to date)
  * directory[/Users/leonardbogdonoff/.bash_it/aliases/enabled] action create[2016-01-27T17:34:11-05:00] INFO: Processing directory[/Users/leonardbogdonoff/.bash_it/aliases/enabled] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb line 15)
 (skipped due to not_if)
  * link[/Users/leonardbogdonoff/.bash_it/aliases/enabled/general.aliases.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing link[/Users/leonardbogdonoff/.bash_it/aliases/enabled/general.aliases.bash] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb line 21)
 (skipped due to not_if)
  * sprout_base_bash_it_enable_feature[completion/defaults] action create[2016-01-27T17:34:11-05:00] INFO: Processing sprout_base_bash_it_enable_feature[completion/defaults] action create (sprout-base::bash_it line 29)
 (up to date)
  * directory[/Users/leonardbogdonoff/.bash_it/completion/enabled] action create[2016-01-27T17:34:11-05:00] INFO: Processing directory[/Users/leonardbogdonoff/.bash_it/completion/enabled] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb line 15)
 (skipped due to not_if)
  * link[/Users/leonardbogdonoff/.bash_it/completion/enabled/defaults.completion.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing link[/Users/leonardbogdonoff/.bash_it/completion/enabled/defaults.completion.bash] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb line 21)
 (skipped due to not_if)
  * sprout_base_bash_it_enable_feature[completion/git] action create[2016-01-27T17:34:11-05:00] INFO: Processing sprout_base_bash_it_enable_feature[completion/git] action create (sprout-base::bash_it line 29)
[2016-01-27T17:34:11-05:00] WARN: Cloning resource attributes for directory[/Users/leonardbogdonoff/.bash_it/completion/enabled] from prior resource (CHEF-3694)
[2016-01-27T17:34:11-05:00] WARN: Previous directory[/Users/leonardbogdonoff/.bash_it/completion/enabled]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb:15:in `block in class_from_file'
[2016-01-27T17:34:11-05:00] WARN: Current  directory[/Users/leonardbogdonoff/.bash_it/completion/enabled]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb:15:in `block in class_from_file'
 (up to date)
  * directory[/Users/leonardbogdonoff/.bash_it/completion/enabled] action create[2016-01-27T17:34:11-05:00] INFO: Processing directory[/Users/leonardbogdonoff/.bash_it/completion/enabled] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb line 15)
 (skipped due to not_if)
  * link[/Users/leonardbogdonoff/.bash_it/completion/enabled/git.completion.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing link[/Users/leonardbogdonoff/.bash_it/completion/enabled/git.completion.bash] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb line 21)
 (skipped due to not_if)
  * sprout_base_bash_it_enable_feature[plugins/ssh] action create[2016-01-27T17:34:11-05:00] INFO: Processing sprout_base_bash_it_enable_feature[plugins/ssh] action create (sprout-base::bash_it line 29)
 (up to date)
  * directory[/Users/leonardbogdonoff/.bash_it/plugins/enabled] action create[2016-01-27T17:34:11-05:00] INFO: Processing directory[/Users/leonardbogdonoff/.bash_it/plugins/enabled] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb line 15)
 (skipped due to not_if)
  * link[/Users/leonardbogdonoff/.bash_it/plugins/enabled/ssh.plugin.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing link[/Users/leonardbogdonoff/.bash_it/plugins/enabled/ssh.plugin.bash] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_enable_feature.rb line 21)
 (skipped due to not_if)
  * sprout_base_bash_it_custom_plugin[bash_it/custom/disable_ctrl-s_output_control.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing sprout_base_bash_it_custom_plugin[bash_it/custom/disable_ctrl-s_output_control.bash] action create (sprout-base::bash_it line 35)
 (up to date)
  * template[/Users/leonardbogdonoff/.bash_it/custom/disable_ctrl-s_output_control.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing template[/Users/leonardbogdonoff/.bash_it/custom/disable_ctrl-s_output_control.bash] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_custom_plugin.rb line 5)
 (up to date)
  * sprout_base_bash_it_custom_plugin[bash_it/custom/enable_ctrl-o_history_execution.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing sprout_base_bash_it_custom_plugin[bash_it/custom/enable_ctrl-o_history_execution.bash] action create (sprout-base::bash_it line 35)
 (up to date)
  * template[/Users/leonardbogdonoff/.bash_it/custom/enable_ctrl-o_history_execution.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing template[/Users/leonardbogdonoff/.bash_it/custom/enable_ctrl-o_history_execution.bash] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_custom_plugin.rb line 5)
 (up to date)
  * sprout_base_bash_it_custom_plugin[bash_it/custom/ensure_usr_local_bin_first.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing sprout_base_bash_it_custom_plugin[bash_it/custom/ensure_usr_local_bin_first.bash] action create (sprout-base::bash_it line 35)
 (up to date)
  * template[/Users/leonardbogdonoff/.bash_it/custom/ensure_usr_local_bin_first.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing template[/Users/leonardbogdonoff/.bash_it/custom/ensure_usr_local_bin_first.bash] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_custom_plugin.rb line 5)
 (up to date)
  * sprout_base_bash_it_custom_plugin[bash_it/custom/add_user_initials_to_git_prompt_info.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing sprout_base_bash_it_custom_plugin[bash_it/custom/add_user_initials_to_git_prompt_info.bash] action create (sprout-base::bash_it line 35)
 (up to date)
  * template[/Users/leonardbogdonoff/.bash_it/custom/add_user_initials_to_git_prompt_info.bash] action create[2016-01-27T17:34:11-05:00] INFO: Processing template[/Users/leonardbogdonoff/.bash_it/custom/add_user_initials_to_git_prompt_info.bash] action create (/Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-base/providers/bash_it_custom_plugin.rb line 5)
 (up to date)
Recipe: sprout-base::user_owns_usr_local
  * directory[/usr/local/bin] action create[2016-01-27T17:34:11-05:00] INFO: Processing directory[/usr/local/bin] action create (sprout-base::user_owns_usr_local line 1)
 (up to date)
  * execute[your current user owns /usr/local] action run[2016-01-27T17:34:11-05:00] INFO: Processing execute[your current user owns /usr/local] action run (sprout-base::user_owns_usr_local line 6)
[2016-01-27T17:34:11-05:00] INFO: execute[your current user owns /usr/local] ran successfully

    - execute chown -R leonardbogdonoff /usr/local
Recipe: sprout-base::homebrew
  * directory[/var/chef/cache] action create[2016-01-27T17:34:11-05:00] INFO: Processing directory[/var/chef/cache] action create (sprout-base::homebrew line 11)
[2016-01-27T17:34:11-05:00] INFO: directory[/var/chef/cache] group changed to 20
[2016-01-27T17:34:11-05:00] INFO: directory[/var/chef/cache] mode changed to 775

    - change mode from '0777' to '0775'
    - change group from 'admin' to 'staff'
  * git[/var/chef/cache/homebrew] action sync[2016-01-27T17:34:11-05:00] INFO: Processing git[/var/chef/cache/homebrew] action sync (sprout-base::homebrew line 19)
 (up to date)
  * execute[Copying homebrew's .git to /usr/local] action run[2016-01-27T17:34:12-05:00] INFO: Processing execute[Copying homebrew's .git to /usr/local] action run (sprout-base::homebrew line 26)
[2016-01-27T17:34:12-05:00] INFO: execute[Copying homebrew's .git to /usr/local] ran successfully

    - execute rsync -axSH /var/chef/cache/homebrew/ /usr/local/
  * execute[Run git clean in /usr/local to clear out cruft after rsync] action run[2016-01-27T17:34:12-05:00] INFO: Processing execute[Run git clean in /usr/local to clear out cruft after rsync] action run (sprout-base::homebrew line 31)
[2016-01-27T17:34:12-05:00] INFO: execute[Run git clean in /usr/local to clear out cruft after rsync] ran successfully

    - execute cd /usr/local; git clean -fd
  * ruby_block[Check that homebrew is running & working] action run[2016-01-27T17:34:12-05:00] INFO: Processing ruby_block[Check that homebrew is running & working] action run (sprout-base::homebrew line 36)
[2016-01-27T17:34:13-05:00] INFO: ruby_block[Check that homebrew is running & working] called

    - execute the ruby block Check that homebrew is running & working
  * directory[/usr/local/sbin] action create[2016-01-27T17:34:13-05:00] INFO: Processing directory[/usr/local/sbin] action create (sprout-base::homebrew line 45)
 (up to date)
  * directory[/Users/leonardbogdonoff/Applications] action create[2016-01-27T17:34:13-05:00] INFO: Processing directory[/Users/leonardbogdonoff/Applications] action create (sprout-base::homebrew line 49)
 (up to date)
Recipe: homebrew::default
  * remote_file[/var/chef/cache/homebrew_go] action create[2016-01-27T17:34:13-05:00] INFO: Processing remote_file[/var/chef/cache/homebrew_go] action create (homebrew::default line 29)
 (up to date)
  * execute[install homebrew] action run[2016-01-27T17:34:13-05:00] INFO: Processing execute[install homebrew] action run (homebrew::default line 34)
 (skipped due to not_if)
  * homebrew_package[git] action install[2016-01-27T17:34:13-05:00] INFO: Processing homebrew_package[git] action install (homebrew::default line 41)
 (skipped due to not_if)
  * execute[update homebrew from github] action run[2016-01-27T17:34:13-05:00] INFO: Processing execute[update homebrew from github] action run (homebrew::default line 45)
Updated Homebrew from b73e1a4 to 84d29a1.
No changes to formulae.
[2016-01-27T17:34:15-05:00] INFO: execute[update homebrew from github] ran successfully

    - execute /usr/local/bin/brew update || true
Recipe: sprout-homebrew::casks
  * sprout_homebrew_cask[ccmenu] action install[2016-01-27T17:34:15-05:00] INFO: Processing sprout_homebrew_cask[ccmenu] action install (sprout-homebrew::casks line 7)
[2016-01-27T17:34:15-05:00] WARN: Cloning resource attributes for homebrew_package[caskroom/cask/brew-cask] from prior resource (CHEF-3694)
[2016-01-27T17:34:15-05:00] WARN: Previous homebrew_package[caskroom/cask/brew-cask]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-homebrew/recipes/cask.rb:13:in `from_file'
[2016-01-27T17:34:15-05:00] WARN: Current  homebrew_package[caskroom/cask/brew-cask]: /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-homebrew/recipes/cask.rb:15:in `from_file'

  
Recipe: sprout-homebrew::cask
  * directory[/usr/local/Library/Taps] action create[2016-01-27T17:34:15-05:00] INFO: Processing directory[/usr/local/Library/Taps] action create (sprout-homebrew::cask line 3)
 (up to date)
  * execute[tap cask] action run[2016-01-27T17:34:15-05:00] INFO: Processing execute[tap cask] action run (sprout-homebrew::cask line 8)
Warning: Tap caskroom/cask already tapped.
[2016-01-27T17:34:15-05:00] INFO: execute[tap cask] ran successfully

    - execute brew tap "caskroom/homebrew-cask"
  * homebrew_package[caskroom/cask/brew-cask] action install[2016-01-27T17:34:15-05:00] INFO: Processing homebrew_package[caskroom/cask/brew-cask] action install (sprout-homebrew::cask line 13)
Error: HOMEBREW_BREW_FILE was not exported! Please call bin/brew directly!

    
    ================================================================================
    Error executing action `install` on resource 'homebrew_package[caskroom/cask/brew-cask]'
    ================================================================================
    
    SystemExit
    ----------
    exit
    
    Cookbook Trace:
    ---------------
    /Users/leonardbogdonoff/sprout-wrap/cookbooks/homebrew/libraries/homebrew_package.rb:94:in `require'
    /Users/leonardbogdonoff/sprout-wrap/cookbooks/homebrew/libraries/homebrew_package.rb:94:in `get_version_from_formula'
    /Users/leonardbogdonoff/sprout-wrap/cookbooks/homebrew/libraries/homebrew_package.rb:74:in `current_installed_version'
    /Users/leonardbogdonoff/sprout-wrap/cookbooks/homebrew/libraries/homebrew_package.rb:44:in `load_current_resource'
    
    Resource Declaration:
    ---------------------
    # In /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-homebrew/recipes/cask.rb
    
     13: package 'caskroom/cask/brew-cask'
     14: 
    
    Compiled Resource:
    ------------------
    # Declared in /Users/leonardbogdonoff/sprout-wrap/cookbooks/sprout-homebrew/recipes/cask.rb:13:in `from_file'
    
    homebrew_package("caskroom/cask/brew-cask") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "caskroom/cask/brew-cask"
      declared_type :package
      cookbook_name :"sprout-homebrew"
      recipe_name "cask"
    end
    
[2016-01-27T17:34:15-05:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2016-01-27T17:34:15-05:00] ERROR: Running exception handlers
Running handlers complete
[2016-01-27T17:34:15-05:00] ERROR: Exception handlers complete
Chef Client failed. 11 resources updated in 8.250292 seconds
[2016-01-27T17:34:15-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-01-27T17:34:15-05:00] ERROR: homebrew_package[caskroom/cask/brew-cask] (sprout-homebrew::cask line 13) had an error: SystemExit: exit
[2016-01-27T17:34:15-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by erickrom** [comment]
+1

**Comment by erickrom** [comment]
Actually is working for me now after syncing my fork with the upstream copy, @wendorf added a few commits recently on cask issues.  Update your copy and try it again.

**Comment by wendorf** [comment]
Hi @rememberlenny ,

As @erickrom mentioned, I believe the recent commits to sprout-wrap and the cookbooks it depends on should resolve the issue you are having. It would be great if you could try again after pulling the latest changes, and let us know if you are still having problems.


Thanks!

**Comment by rememberlenny** [comment]
Thank you!



--
Leonard Bogdonoff
949-322-8496 | @rememberlenny

**Comment by rememberlenny** [comment]
Ran it and its good!
